version: '3.9'

services:
  backend:
    build: .
    container_name: finance_advisor_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    environment:
      - DATABASE_URL=sqlite:///./database.sqlite
    depends_on:
      - ollama
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data: